config/routes.rb
Rails.application.routes.draw do
  get "/", to: "home#index", as: :root
  delete '/session', to: 'sessions#destroy', as: :session_path

  resources :meals, :users, :servings, :portions, :sessions

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :user
  has_many :portions
end

app/models/portion.rb
class Portion < ActiveRecord::Base
  belongs_to :meal
  belongs_to :serving

  def calories
    self.serving.calories * self.grams / self.serving.grams
  end

  def to_oz
    (self.grams * 0.035274).to_i
  end
end

app/models/serving.rb
class Serving < ActiveRecord::Base
  has_many :portions
  has_many :meals, through: :portions
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :meals
  has_many :portions, through: :meals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :current_user

  private

  def g_to_o grams
    grams * 0.035274
  end

  def o_to_g ozs
    ozs / 0.035274
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if (session[:user_id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end
  
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def show
    @meal = Meal.find(params[:id])
  end

  def create
    @meal = Meal.new(meal_params)
    if @meal.save
      redirect_to @meal
    else
      flash[:notice] = "There was an internal error and the meal could not be saved."
      redirect_to root_path
    end
  end

  def show
    @meal = Meal.find(params[:id])
    unless @meal.user == @current_user
      flash[:notice] = "You are not authorized to see this page."
      redirect_to root_path
    end
    @servings = Serving.all
  end

  private

  def meal_params
    params.require(:meal).permit(:date_eaten, :user_id)
  end

  def portion_params

  end

end

app/controllers/portions_controller.rb
class PortionsController < ApplicationController

  def create
    @portion = Portion.new(portion_params)
    if @portion.save
      redirect_to @portion.meal
    else
      flash[:notice] = "The portion was unable to save"
      redirect_to root_path
    end
  end

  private

  def portion_params
    z = params.require(:portion).permit(:grams, :meal_id, :serving_id)
    if params[:units] == 'ounces'
      z[:grams] = o_to_g z[:grams].to_i
    end
    return z
  end
end

app/controllers/servings_controller.rb
class ServingsController < ApplicationController

  def index
    @servings = Serving.all
  end

  def create
    @serving = Serving.new(serving_params)
    if @serving.save
      redirect_to @current_user
    else
      flash[:notice] = "The serving could not be saved.
                        Please try again at another time."
      redirect_to root_path
    end
  end

  private

  def serving_params
    z = params.require(:serving).permit(:name,
                                    :grams,
                                    :calories,
                                    :susan_approved,
                                    :susan_limit)
    if params[:units] == 'ounces'
       z[:grams] = o_to_g z[:grams].to_i
    end
    return z
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  def create
    @user = User.find_by('name = ? AND password = ?', params[:name], params[:password])
    if @user
      session[:user_id] = @user.id
    else
      flash[:notice] = "Incorrect or non-existant user name or password."
    end
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(params.require(:user).permit(:name, :email, :password))
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:notice] = "There was an internal server error and this user could not be saved."
      redirect_to root_path
    end
  end

  def show
    @servings = Serving.all
    @user = User.find(session[:user_id])
    unless @user.id == params[:id].to_i
      flash[:notice] = "You are not authorized to visit that user's page."
      redirect_to root_path
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/portions_helper.rb
module PortionsHelper
end

app/helpers/servings_helper.rb
module ServingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% if !@current_user %>
  <button type="button" class="btn btn-default" data-toggle="modal" data-target="#signInModal">
    Sign In
  </button>

  <button type="button" class="btn btn-default" data-toggle="modal" data-target="#signUpModal">
    Sign Up
  </button>
  <% end %>
<br>
<% if flash[:notice] %>
  <br>
  <div class="alert alert-success" role="alert">
    <div class="center"> <%= flash[:notice] %> </div>
  </div>
<% end %>
<br>
<div id='serving_button_div', class='text-center'>
<%= link_to "Servings", servings_path, class: "btn btn-default", id: 'food-button' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Susan's Servings</title>
  <link rel="stylesheet" href="stylesheets/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <!-- Optional theme -->
  <link href='http://fonts.googleapis.com/css?family=Alex+Brush' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class='col-sm-12'>
    <h1>Susan's Servings</h1>
    <hr>
      <% if @current_user %>
          <%= link_to "My Account", @current_user, class: "btn btn-default" %>
          <%= link_to "Sign Out", session_path(0), method: :delete, class: "btn btn-default" %>
        <hr>
      <% end %>
      <%= render "/shared/modals.html.erb" %>
  </header>
<div class='col-md-10'>
  <%= yield %>
</div>

</body>
</html>

app/views/meals/show.html.erb
On <%= @meal.date_eaten.strftime("%B %-d, %Y at %l:%M %P") %> you ate ...<br>

<% if @meal.portions.length > 0 %>
  <% cals = 0 %>
  <ul>
    <% @meal.portions.each do |p| %>
      <% cals += p.calories %>
      <% p.serving.susan_approved && p.grams <= (p.serving.grams * p.serving.susan_limit) ? approved = "approved of this serving." : approved = "did not approve of this serving." %>
      <li>
        <%= p.grams %> grams (<%= p.to_oz %> ounces) of
        <%= p.serving.name.downcase %>.
        This was <%= p.calories %> calories. Susan <%= approved %>
      </li>
    <% end %>
  </ul>
  During this meal, you consumed a total of <%= cals %> calories.
<% end %>
<hr>
<h3> Add more portions: </h3> <br>
<% @servings.each do |serving| %>
  <h3> <%= serving.name %> </h3>
  <%= bootstrap_form_for Portion.new, url: '/portions', layout: :inline do |f| %>
    <%= f.text_field :grams, label: 'Portion size ' %>
    <%= label_tag :units, "Units " %>
    <%= select_tag :units, "<option>ounces</option><option>grams</option>".html_safe %>
    <%= f.hidden_field :meal_id, value: @meal.id %>
    <%= f.hidden_field :serving_id, value: serving.id %>
    <%= f.submit "Add serving", class: 'btn btn-default' %>
  <% end %> <br>
<% end %>
<hr>
Not seeing the serving you need?
<button type="button" class="btn btn-default" data-toggle="modal" data-target="#newServingModal">
  Add a serving
</button>
<br><br><br>

app/views/servings/index.html.erb
<h1>Servings</h1>
<ul>
<% @servings.each do |s| %>
  <li><%= s.name %></li>
<% end %>
</ul>

app/views/shared/_modals.html.erb
<% if @current_user %>
  <div class="modal fade" id="newMealModal" tabindex="-1" role="dialog" aria-labelledby="newMealModalLabel" aria-hidden="true" data-backdrop = "false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">Sign Up</h4>
        </div>
        <div class="modal-body">
          <%= bootstrap_form_for Meal.new, url: meals_path do |f| %>
            <%= f.hidden_field :user_id, value: @current_user.id %>
            <%= f.datetime_select :date_eaten, label: 'When did you eat this meal?' %> <br>
        </div>         <!-- end modal body -->
        <div class="modal-footer">
            <%= f.submit "Register Meal", class: "btn btn-default"%>
            <% end %>
        </div>        <!-- end modal footer -->
      </div>      <!-- end modal content -->
    </div>
  </div>

  <div class="modal fade" id="newServingModal" tabindex="-1" role="dialog" aria-labelledby="newServingModalLabel" aria-hidden="true" data-backdrop = "false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">Add a serving</h4>
        </div>
        <div class="modal-body">
          <%= bootstrap_form_for Serving.new, url: servings_path do |f| %>
            <% options = [true, false] %>
            <% units = ['ounces', 'grams'] %>
            <%= f.text_field :name, label: "Name" %>
            <%= f.text_field :grams, label: 'Weight' %>
            <%= label_tag :units, "Units" %>
            <%= select_tag :units, "<option>ounces</option><option>grams</option>".html_safe %> <br><br>
            <%= f.text_field :calories, label: 'Caloric content' %>

            <%= f.select :susan_approved, options, label: "Susan approves of this food." %>
            <%= f.text_field :susan_limit, label: "How many of these servings would Susan allow in a day?" %>
            <br>
        </div>         <!-- end modal body -->
        <div class="modal-footer">
            <%= f.submit "Register Serving", class: "btn btn-default"%>
            <% end %>
        </div>        <!-- end modal footer -->
      </div>      <!-- end modal content -->
    </div>
  </div>
<% else %>
  <div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="signUpModalLabel" aria-hidden="true" data-backdrop = "false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">Sign Up</h4>
        </div>
        <div class="modal-body">
          <%= form_for User.new, url: users_path do |f| %>
            <%= f.label :name, "User name" %><br>
            <%= f.text_field :name %> <br>
            <%= f.label :email, "Email address" %><br>
            <%= f.text_field :email, type: 'email' %> <br>
            <%= f.label :password, "Password" %><br>
            <%= f.text_field :password, type: 'password' %>
        </div>         <!-- end modal body -->
        <div class="modal-footer">
            <%= f.submit "Sign Up", class: "btn btn-default"%>
            <% end %>
        </div>    <!-- end modal footer -->
      </div>   <!-- end modal content -->
    </div>
  </div>

  <div class="modal fade" id="signInModal" tabindex="-1" role="dialog" aria-labelledby="signInModalLabel" aria-hidden="true" data-backdrop = "false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">Sign In</h4>
        </div>
        <div class="modal-body">
          <%= form_tag sessions_path %>
            <%= label_tag :name, "User name" %><br>
            <%= text_field_tag :name %> <br>
            <%= label_tag :password, "Password" %><br>
            <%= password_field_tag :password %>
        </div>
        <div class="modal-footer">
            <%= submit_tag "Sign In", class: "btn btn-default"%>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<h3> Hello, <%= @user.name %>! </h3><br>
<button type="button" class="btn btn-default" data-toggle="modal" data-target="#newMealModal">
  Add a meal
</button>
<button type="button" class="btn btn-default" data-toggle="modal" data-target="#newServingModal">
  Add a serving
</button>
<hr>
<% if @user.meals.length > 0 %>
  <% @user.meals.each do |m| %>
    <%= link_to m.date_eaten.strftime("%B %-d, %Y at %l:%M %P"), m %>
    <ul>
      <% m.portions.each do |p| %>
        <li><%= p.serving.name %> <%= p.grams %> grams</li>
      <% end %>
    </ul>
  <% end %>
<% else %>
  You don't have any meals.
<% end %>